/* capture.h — scripted, offscreen capture of the viewer's own chrome.
 *
 * docs/viewer.png was a hand capture, so it went stale the moment the toolbar
 * was restyled and nothing said so. Everything else in the README is
 * regenerated by tools/make_docs.py from a real run; this makes the UI shots
 * regenerated too.
 *
 * A script drives the REAL viewer: the steps below push SDL events into the
 * ordinary event loop, so a scripted click goes through the same hit test,
 * the same undo and the same refusal path a human click does. Nothing here
 * reimplements the app, which is the point -- a capture that drew its own
 * toolbar could agree with the README while disagreeing with the tool.
 *
 * Runs against SDL's dummy video driver, so it needs no window, no display
 * and no accessibility permissions:
 *
 *     SDL_VIDEODRIVER=dummy ./lightsim-view scene.scene \
 *         --capture docs/shots/viewer.cap --capture-out out/shots
 *
 * Script language, one command per line, `#` to end of line is a comment:
 *
 *     wait MS               hold, letting the progressive render advance
 *     key NAME              a key press; NAME is any SDL key name ("A", "Tab",
 *                           "Escape", "3"), optionally prefixed by cmd/shift
 *     move X Y              move the cursor (this is what raises a tooltip)
 *     click X Y             move, press and release
 *     drag X0 Y0 X1 Y1 MS   press, glide over MS, release
 *     drop PATH             drop a file on the window, as a user would
 *     shot NAME             write out_dir/NAME.ppm
 *     record NAME [MS]      write a frame every MS from now on, as
 *                           NAME_0000.ppm...; MS defaults to one frame
 *     stop                  stop recording
 *
 * Time is milliseconds throughout, and a frame is CAPTURE_FRAME_MS, so a
 * recorded stretch plays back at a known rate whatever the machine's speed.
 */
#ifndef LIGHTSIM_VIEWER_CAPTURE_H
#define LIGHTSIM_VIEWER_CAPTURE_H

#include <SDL2/SDL.h>
#include <stdbool.h>
#include <stddef.h>

/* 25 fps. The loop is paced to this rather than run flat out: the render
 * thread refines progressively, so frame N of a capture has to mean the same
 * amount of settling on every machine or the shots are not reproducible. */
#define CAPTURE_FRAME_MS 40

typedef struct Capture Capture;

/* Parses `script_path` up front -- a typo on the last line should not surface
 * forty seconds into a run. Returns NULL and fills `err` on failure. */
Capture *capture_open(const char *script_path, const char *out_dir,
                      char *err, size_t errn);
void capture_free(Capture *c);

/* Top of the frame, before events are polled: pushes whatever input this
 * frame calls for. Returns false when the script has run out, which is the
 * capture's way of asking the loop to exit. */
bool capture_begin_frame(Capture *c);

/* End of the frame, after everything is drawn and before the present: writes
 * a PPM if this frame is a shot or part of a recording, then paces the frame
 * out to CAPTURE_FRAME_MS. */
void capture_end_frame(Capture *c, SDL_Renderer *ren);

/* How many files were written, for the closing line on stdout. */
int capture_written(const Capture *c);

#endif /* LIGHTSIM_VIEWER_CAPTURE_H */
