#include "lightsim/export.h"
#include "lightsim/film.h"
#include "lightsim/color.h"
#include <stdio.h>
#include <math.h>

/* A spectrum's chromaticity as a display colour, normalised so the brightest
 * channel is 1. Carries the source's hue across without also carrying its
 * intensity -- intensity is the light's power, set separately. */
static void spectrum_to_tint(const Spectrum *s, double rgb[3]) {
    RGB c = ls_xyz_to_linear_srgb(ls_spectrum_to_xyz(s));
    double m = fmax(c.r, fmax(c.g, c.b));
    if (m <= 0.0) { rgb[0] = rgb[1] = rgb[2] = 1.0; return; }
    rgb[0] = ls_clamp(c.r / m, 0.0, 1.0);
    rgb[1] = ls_clamp(c.g / m, 0.0, 1.0);
    rgb[2] = ls_clamp(c.b / m, 0.0, 1.0);
}

/* A reflectance shown as a display colour.
 *
 * A reflectance is not an emitter: it has no colour until something shines on
 * it. Pushing rho straight through XYZ implicitly views it under an
 * equal-energy illuminant, and since sRGB's white point is D65 that renders a
 * neutral grey as noticeably warm. Viewing it under D65 and normalising by
 * that illuminant's own luminance is the correct reduction, and it sends a
 * flat rho of 0.8 to exactly (0.8, 0.8, 0.8). */
static void albedo_to_rgb(const Spectrum *rho, double rgb[3]) {
    Spectrum d65 = ls_spectrum_daylight(6504.0);
    Spectrum seen = ls_spectrum_mul(*rho, d65);
    XYZ c = ls_spectrum_to_xyz(&seen);
    XYZ w = ls_spectrum_to_xyz(&d65);
    if (w.y <= 0.0) { rgb[0] = rgb[1] = rgb[2] = 0.0; return; }
    XYZ norm = { c.x / w.y, c.y / w.y, c.z / w.y };
    RGB o = ls_xyz_to_linear_srgb(norm);
    rgb[0] = ls_clamp(o.r, 0.0, 1.0);
    rgb[1] = ls_clamp(o.g, 0.0, 1.0);
    rgb[2] = ls_clamp(o.b, 0.0, 1.0);
}

static void basis_for(vec3 n, vec3 *t, vec3 *b) {
    Basis o = ls_basis(v3norm(n));
    *t = o.t; *b = o.b;
}

bool ls_export_blender(const SceneDesc *d,
                       const ls_real *grid, int nu, int nv,
                       ls_real lo, ls_real hi, const char *unit_name,
                       const char *quantity_name, const char *path) {
    FILE *f = fopen(path, "w");
    if (!f) return false;

    fprintf(f,
        "import bpy\n"
        "import math\n\n"
        "# Generated by lightsim. Convention: 1 world unit = 1 metre.\n"
        "# Light power is the SAME radiant flux in watts the simulation used --\n"
        "# Cycles reads area-light power as radiant flux, so a Cycles render of\n"
        "# this scene is directly comparable with the simulated field below.\n"
        "#\n"
        "# Quantity mapped onto FieldGrid: %s (%s), %.6g to %.6g.\n\n",
        quantity_name, unit_name, (double)lo, (double)hi);

    fprintf(f,
        "SCENE_NAME = \"lightsim\"\n"
        "FIELD_EMISSION_STRENGTH = 1.0   # raise if the map looks dim in Rendered view\n"
        "SHOW_FIELD_AS_EMISSION = True   # False -> plain diffuse, lit by the scene\n\n");

    /* ---------------- geometry ---------------- */
    fprintf(f, "# (name, kind, params...) -- kind drives the builder below.\n");
    fprintf(f, "QUADS = [\n");
    for (int i = 0; i < d->nprims; ++i) {
        const Prim *p = &d->prims[i];
        if (p->kind != LS_PRIM_QUAD && p->kind != LS_PRIM_PLANE) continue;
        const Material *m = &d->mats[p->mat_id];
        double rgb[3];
        if (m->emissive) spectrum_to_tint(&m->le, rgb); else albedo_to_rgb(&m->bsdf.rho, rgb);
        vec3 ex = p->ex, ey = p->ey;
        if (p->kind == LS_PRIM_PLANE) {          /* give the plane a finite size */
            vec3 t, b; basis_for(p->n, &t, &b);
            ex = v3scale(t, 2.0); ey = v3scale(b, 2.0);
        }
        fprintf(f, "    (\"Surface_%d\", (%.6g,%.6g,%.6g), (%.6g,%.6g,%.6g), (%.6g,%.6g,%.6g),"
                   " (%.4f,%.4f,%.4f), %s),\n",
                i, p->c.x, p->c.y, p->c.z, ex.x, ex.y, ex.z, ey.x, ey.y, ey.z,
                rgb[0], rgb[1], rgb[2], m->emissive ? "True" : "False");
    }
    fprintf(f, "]\n\n");

    fprintf(f, "SPHERES = [\n");
    for (int i = 0; i < d->nprims; ++i) {
        const Prim *p = &d->prims[i];
        if (p->kind != LS_PRIM_SPHERE) continue;
        const Material *m = &d->mats[p->mat_id];
        double rgb[3];
        if (m->emissive) spectrum_to_tint(&m->le, rgb); else albedo_to_rgb(&m->bsdf.rho, rgb);
        fprintf(f, "    (\"Part_%d\", (%.6g,%.6g,%.6g), %.6g, (%.4f,%.4f,%.4f), %s),\n",
                i, p->c.x, p->c.y, p->c.z, p->r, rgb[0], rgb[1], rgb[2],
                m->emissive ? "True" : "False");
    }
    fprintf(f, "]\n\n");

    fprintf(f, "DISKS = [\n");
    for (int i = 0; i < d->nprims; ++i) {
        const Prim *p = &d->prims[i];
        if (p->kind != LS_PRIM_DISK) continue;
        const Material *m = &d->mats[p->mat_id];
        double rgb[3];
        if (m->emissive) spectrum_to_tint(&m->le, rgb); else albedo_to_rgb(&m->bsdf.rho, rgb);
        fprintf(f, "    (\"Disk_%d\", (%.6g,%.6g,%.6g), (%.6g,%.6g,%.6g), %.6g,"
                   " (%.4f,%.4f,%.4f), %s),\n",
                i, p->c.x, p->c.y, p->c.z, p->n.x, p->n.y, p->n.z, p->r,
                rgb[0], rgb[1], rgb[2], m->emissive ? "True" : "False");
    }
    fprintf(f, "]\n\n");

    /* ---------------- lights ---------------- */
    fprintf(f, "# (name, type, location, direction, size_u, size_v, watts, rgb, spot_deg)\n");
    fprintf(f, "LIGHTS = [\n");
    for (int i = 0; i < d->nlights; ++i) {
        const Light *l = &d->lights[i];
        double rgb[3];
        spectrum_to_tint(&l->s_hat, rgb);
        const char *type = "POINT";
        double su = 0.0, sv = 0.0, spot = 0.0, watts = l->phi_e;
        vec3 dir = l->n;
        switch (l->kind) {
            case LS_LIGHT_POINT: type = "POINT"; break;
            case LS_LIGHT_SPOT:
                type = "SPOT";
                spot = 2.0 * acos(ls_clamp(l->cos_total, -1.0, 1.0)) * 180.0 / LS_PI;
                break;
            case LS_LIGHT_DIRECTIONAL:
                type = "SUN";
                /* Blender SUN strength is irradiance on a perpendicular
                 * surface, W/m^2 -- the same quantity e_perp holds. */
                watts = l->e_perp;
                break;
            case LS_LIGHT_RECT:
                type = "AREA";
                su = 2.0 * v3len(l->ex); sv = 2.0 * v3len(l->ey);
                break;
            case LS_LIGHT_DISK:
                type = "AREA_DISK"; su = sv = 2.0 * l->radius; break;
            case LS_LIGHT_SPHERE:
                type = "POINT"; su = sv = l->radius; break;
        }
        fprintf(f, "    (\"Light_%d\", \"%s\", (%.6g,%.6g,%.6g), (%.6g,%.6g,%.6g),"
                   " %.6g, %.6g, %.8g, (%.4f,%.4f,%.4f), %.4f),\n",
                i, type, l->p.x, l->p.y, l->p.z, dir.x, dir.y, dir.z,
                su, sv, watts, rgb[0], rgb[1], rgb[2], spot);
    }
    fprintf(f, "]\n\n");

    /* ---------------- measured field ---------------- */
    fprintf(f, "FIELD = {\n");
    fprintf(f, "    \"origin\": (%.6g,%.6g,%.6g),\n", d->grid_o.x, d->grid_o.y, d->grid_o.z);
    fprintf(f, "    \"u\": (%.6g,%.6g,%.6g),\n", d->grid_u.x, d->grid_u.y, d->grid_u.z);
    fprintf(f, "    \"v\": (%.6g,%.6g,%.6g),\n", d->grid_v.x, d->grid_v.y, d->grid_v.z);
    fprintf(f, "    \"nu\": %d, \"nv\": %d,\n", nu, nv);
    fprintf(f, "    \"unit\": \"%s\", \"quantity\": \"%s\",\n", unit_name, quantity_name);
    fprintf(f, "    \"lo\": %.8g, \"hi\": %.8g,\n", (double)lo, (double)hi);
    fprintf(f, "}\n\n");

    /* Per-cell colour, already through the viridis ramp, plus the raw value so
     * the numbers survive the trip and can be read back in Blender. */
    fprintf(f, "# One entry per measurement point: (value, r, g, b)\n");
    fprintf(f, "CELLS = [\n");
    ls_real span = (hi > lo) ? (hi - lo) : 1.0;
    for (int j = 0; j < nv; ++j) {
        fprintf(f, "    ");
        for (int i = 0; i < nu; ++i) {
            ls_real v = grid[(size_t)j * (size_t)nu + (size_t)i];
            RGB c = ls_colormap_viridis((v - lo) / span);
            fprintf(f, "(%.6g,%.3f,%.3f,%.3f),", (double)v, c.r, c.g, c.b);
        }
        fprintf(f, "\n");
    }
    fprintf(f, "]\n\n");

    /* ---------------- builder ---------------- */
    fprintf(f, "%s",
        "def rgb_material(name, rgb, emissive=False, strength=1.0):\n"
        "    mat = bpy.data.materials.new(name)\n"
        "    mat.use_nodes = True\n"
        "    nt = mat.node_tree\n"
        "    for n in list(nt.nodes):\n"
        "        nt.nodes.remove(n)\n"
        "    out = nt.nodes.new('ShaderNodeOutputMaterial')\n"
        "    if emissive:\n"
        "        sh = nt.nodes.new('ShaderNodeEmission')\n"
        "        sh.inputs['Color'].default_value = (rgb[0], rgb[1], rgb[2], 1.0)\n"
        "        sh.inputs['Strength'].default_value = strength\n"
        "    else:\n"
        "        sh = nt.nodes.new('ShaderNodeBsdfDiffuse')\n"
        "        sh.inputs['Color'].default_value = (rgb[0], rgb[1], rgb[2], 1.0)\n"
        "    nt.links.new(sh.outputs[0], out.inputs['Surface'])\n"
        "    return mat\n"
        "\n"
        "\n"
        "def add_mesh(name, verts, faces, mat):\n"
        "    mesh = bpy.data.meshes.new(name)\n"
        "    mesh.from_pydata(verts, [], faces)\n"
        "    mesh.validate()\n"
        "    mesh.update()\n"
        "    obj = bpy.data.objects.new(name, mesh)\n"
        "    if mat is not None:\n"
        "        obj.data.materials.append(mat)\n"
        "    bpy.context.scene.collection.objects.link(obj)\n"
        "    return obj\n"
        "\n"
        "\n"
        "def add_quad(name, c, ex, ey, rgb, emissive):\n"
        "    # The simulator's quad spans c +/- ex +/- ey (half-edge vectors).\n"
        "    verts = [\n"
        "        (c[0]-ex[0]-ey[0], c[1]-ex[1]-ey[1], c[2]-ex[2]-ey[2]),\n"
        "        (c[0]+ex[0]-ey[0], c[1]+ex[1]-ey[1], c[2]+ex[2]-ey[2]),\n"
        "        (c[0]+ex[0]+ey[0], c[1]+ex[1]+ey[1], c[2]+ex[2]+ey[2]),\n"
        "        (c[0]-ex[0]+ey[0], c[1]-ex[1]+ey[1], c[2]-ex[2]+ey[2]),\n"
        "    ]\n"
        "    return add_mesh(name, verts, [(0, 1, 2, 3)],\n"
        "                    rgb_material(name + '_Mat', rgb, emissive))\n"
        "\n"
        "\n"
        "def look_along(obj, d):\n"
        "    import mathutils\n"
        "    v = mathutils.Vector((d[0], d[1], d[2]))\n"
        "    if v.length == 0.0:\n"
        "        return\n"
        "    obj.rotation_mode = 'QUATERNION'\n"
        "    # Blender lights emit along -Z, which is the convention the\n"
        "    # simulator's spot/area direction vector already uses.\n"
        "    obj.rotation_quaternion = v.normalized().to_track_quat('-Z', 'Y')\n"
        "\n"
        "\n");

    fprintf(f, "%s",
        "for (name, c, ex, ey, rgb, emissive) in QUADS:\n"
        "    add_quad(name, c, ex, ey, rgb, emissive)\n"
        "\n"
        "for (name, c, r, rgb, emissive) in SPHERES:\n"
        "    bpy.ops.mesh.primitive_uv_sphere_add(radius=r, location=c, segments=48, ring_count=24)\n"
        "    obj = bpy.context.object\n"
        "    obj.name = name\n"
        "    bpy.ops.object.shade_smooth()\n"
        "    obj.data.materials.append(rgb_material(name + '_Mat', rgb, emissive))\n"
        "\n"
        "for (name, c, n, r, rgb, emissive) in DISKS:\n"
        "    bpy.ops.mesh.primitive_circle_add(radius=r, location=c, fill_type='NGON', vertices=64)\n"
        "    obj = bpy.context.object\n"
        "    obj.name = name\n"
        "    look_along(obj, n)\n"
        "    obj.data.materials.append(rgb_material(name + '_Mat', rgb, emissive))\n"
        "\n"
        "for (name, kind, loc, d, su, sv, watts, rgb, spot_deg) in LIGHTS:\n"
        "    btype = 'AREA' if kind.startswith('AREA') else kind\n"
        "    data = bpy.data.lights.new(name=name + '_Data', type=btype)\n"
        "    data.color = rgb\n"
        "    if btype == 'SUN':\n"
        "        data.energy = watts            # irradiance, W/m^2\n"
        "        data.angle = 0.0\n"
        "    else:\n"
        "        data.energy = watts            # radiant flux, W\n"
        "    if btype == 'AREA':\n"
        "        data.shape = 'DISK' if kind == 'AREA_DISK' else 'RECTANGLE'\n"
        "        if data.shape == 'RECTANGLE':\n"
        "            data.size, data.size_y = su, sv\n"
        "        else:\n"
        "            data.size = su\n"
        "    if btype == 'SPOT':\n"
        "        data.spot_size = math.radians(spot_deg)\n"
        "    obj = bpy.data.objects.new(name, data)\n"
        "    obj.location = loc\n"
        "    bpy.context.scene.collection.objects.link(obj)\n"
        "    if btype in ('AREA', 'SPOT', 'SUN'):\n"
        "        look_along(obj, d)\n"
        "\n"
        "\n");

    fprintf(f, "%s",
        "# ---- the measured field, one face per measurement point ----\n"
        "o, U, V = FIELD['origin'], FIELD['u'], FIELD['v']\n"
        "NU, NV = FIELD['nu'], FIELD['nv']\n"
        "verts, faces, cols = [], [], []\n"
        "for j in range(NV + 1):\n"
        "    for i in range(NU + 1):\n"
        "        fu, fv = i / NU, j / NV\n"
        "        verts.append((o[0] + U[0]*fu + V[0]*fv,\n"
        "                      o[1] + U[1]*fu + V[1]*fv,\n"
        "                      o[2] + U[2]*fu + V[2]*fv))\n"
        "stride = NU + 1\n"
        "for j in range(NV):\n"
        "    for i in range(NU):\n"
        "        a = j * stride + i\n"
        "        faces.append((a, a + 1, a + stride + 1, a + stride))\n"
        "        cols.append(CELLS[j * NU + i])\n"
        "\n"
        "field_mat = rgb_material('Field_Mat', (1.0, 1.0, 1.0),\n"
        "                         emissive=SHOW_FIELD_AS_EMISSION,\n"
        "                         strength=FIELD_EMISSION_STRENGTH)\n"
        "field = add_mesh('FieldGrid', verts, faces, field_mat)\n"
        "\n"
        "# Per-face colour through a colour attribute, so the false-colour map\n"
        "# survives into the viewport and into a render.\n"
        "mesh = field.data\n"
        "attr = mesh.color_attributes.new(name='Illuminance', type='FLOAT_COLOR', domain='CORNER')\n"
        "for poly in mesh.polygons:\n"
        "    val, r, g, b = cols[poly.index]\n"
        "    for li in poly.loop_indices:\n"
        "        attr.data[li].color = (r, g, b, 1.0)\n"
        "\n"
        "nt = field_mat.node_tree\n"
        "cattr = nt.nodes.new('ShaderNodeVertexColor')\n"
        "cattr.layer_name = 'Illuminance'\n"
        "shader = [n for n in nt.nodes if n.type in ('EMISSION', 'BSDF_DIFFUSE')][0]\n"
        "nt.links.new(cattr.outputs['Color'], shader.inputs['Color'])\n"
        "\n"
        "# Keep the raw measured value on the mesh too, so it can be read back\n"
        "# in Blender rather than only eyeballed off the ramp.\n"
        "vals = mesh.attributes.new(name='Value', type='FLOAT', domain='FACE')\n"
        "for poly in mesh.polygons:\n"
        "    vals.data[poly.index].value = cols[poly.index][0]\n"
        "\n"
        "scene = bpy.context.scene\n"
        "scene.unit_settings.system = 'METRIC'\n"
        "scene.unit_settings.length_unit = 'METERS'\n"
        "try:\n"
        "    scene.render.engine = 'CYCLES'\n"
        "except TypeError:\n"
        "    pass\n"
        "\n"
        "print('lightsim: %d surfaces, %d lights, %dx%d field (%s, %.4g..%.4g %s)' %\n"
        "      (len(QUADS) + len(SPHERES) + len(DISKS), len(LIGHTS), NU, NV,\n"
        "       FIELD['quantity'], FIELD['lo'], FIELD['hi'], FIELD['unit']))\n");

    fclose(f);
    return true;
}
